In [3]:
import pandas as pd

import os

In [4]:
main_path = "~/Unity_projects/FetalUltrasoundSimulator_test1/AcquiredData/Poses1/"
file_path = "pos_unity.csv"
df = pd.read_csv(os.path.join(main_path, file_path))

print("df ", df.shape)
# Display the first few rows of the DataFrame
print(df.head())

df  (320, 7)
   pos_x  pos_y  pos_z  rot_x  rot_y  rot_z  id
0  -0.04      0 -0.190      0      0      0   0
1  -0.04      0 -0.187      0      0      0   1
2  -0.04      0 -0.184      0      0      0   2
3  -0.04      0 -0.181      0      0      0   3
4  -0.04      0 -0.178      0      0      0   4

In [6]:
main_path = "~/Unity_projects/FetalUltrasoundSimulator_test1/AcquiredData/Poses2/"
file_path = "pos_unity.csv"
df = pd.read_csv(os.path.join(main_path, file_path))

print("df ", df.shape)
# Display the first few rows of the DataFrame
df

df  (320, 7)

     pos_x  pos_y  pos_z  rot_x  rot_y  rot_z   id
0    0.000      0  0.000      0      0      0    0
1    0.000      0  0.003      0      0      0    1
2    0.000      0  0.006      0      0      0    2
3    0.000      0  0.009      0      0      0    3
4    0.000      0  0.012      0      0      0    4
..     ...    ...    ...    ...    ...    ...  ...
315  0.036      0  0.177      0      0      0  315
316  0.036      0  0.180      0      0      0  316
317  0.036      0  0.183      0      0      0  317
318  0.036      0  0.186      0      0      0  318
319  0.036      0  0.189      0      0      0  319

[320 rows x 7 columns]